spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/werty4777/config-repo
server:
  port: 8888


eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
